import Navbar from "./components/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { NextAuthProvider } from "./provider";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextAuthProvider>
          <div className="max-5-xl mx-auto px-8">
            <Navbar />
          </div>
          <div className="pt-16 font-bold">{children}</div>
        </NextAuthProvider>
      </body>
    </html>
  );
}
